/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package deezer;

import java.io.IOException;
import java.sql.SQLException;

public class App {
	public static void main(String[] args) throws IOException, SQLException {
	Menu.choixMenu();
	}
}
